# Generated by Django 5.2.7 on 2025-10-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watches", "0002_alter_smartwatch_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchmetric",
            name="timestamp",
            field=models.BigIntegerField(
                db_index=True, help_text="Unix timestamp (epoch value)"
            ),
        ),
    ]
