# Generated by Django 5.2.7 on 2025-10-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watches", "0003_alter_watchmetric_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("HIGH_HEART_RATE", "High Heart Rate"),
                            ("LOW_HEART_RATE", "Low Heart Rate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("heart_rate", models.PositiveIntegerField()),
                (
                    "timestamp",
                    models.BigIntegerField(
                        db_index=True, help_text="Unix timestamp (epoch value)"
                    ),
                ),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="watches.smartwatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
            },
        ),
    ]
