# Generated by Django 5.2.7 on 2025-10-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watches", "0004_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartwatch",
            name="high_heart_rate_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="High heart rate threshold (BPM). If not specified, uses default 98 BPM.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="smartwatch",
            name="low_heart_rate_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Low heart rate threshold (BPM). If not specified, uses default 25 BPM.",
                null=True,
            ),
        ),
    ]
