# Generated by Django 4.2.25 on 2025-11-10 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watches", "0005_smartwatch_high_heart_rate_threshold_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="smartwatch",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="smartwatch",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="watchmetric",
            name="watch",
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
        migrations.DeleteModel(
            name="SmartWatch",
        ),
        migrations.DeleteModel(
            name="WatchMetric",
        ),
    ]
